### ISSUE TITLE
Remove "eye" from the topic list

### ISSUE THREAD

**Issue by soichih** [DanNBullock/app-voxeleronOCT#2]
This App is creating a category-of-one with "eye" as a github repo topic.

![image](https://user-images.githubusercontent.com/923896/83090114-fcb3bc00-a065-11ea-9519-c5f5732dfadf.png)

Could you consider removing it so that it will be displayed under "vision" category only?

**Comment by DanNBullock** [comment]
@francopestilli requested this category.  I feel that we should run such a change by him before making any changes.  He may be planning on having more such eye-specific (and not just vision) apps.

**Comment by francopestilli** [comment]
@soichih @DanNBullock fine removing eye. I would like to keep vision or vision science

**Comment by DanNBullock** [comment]
change made
