### ISSUE TITLE
brainlife can't handle `git@github.com` url for submodule

### ISSUE THREAD

**Issue by soichih** [DanNBullock/app-voxeleronOCT#3]
@DanNBullock Could you update this app to use `https://github.com` URL for submodule? 

I've just written a note about this in our doc 
>  https://brainlife.io/docs/user/failure/#failed-to-cache-app-code1

Basically, you can just update the content of `.git/config` to include this 

```
[submodule "jsonlab"]
    url = https://github.com/fangq/jsonlab.git
```

**Comment by DanNBullock** [comment]
Updated here:

https://github.com/DanNBullock/app-voxeleronOCT/commit/08aa126f69529345ce213cbcbf07fd737f946054

Also though, I'm not 100% on whether the ".git" component is necessary?  The other module in this repo doesn't have the ".git" component, but I guess we'll see.

(also I managed to tag the wrong Soichi in this somehow.  If you know how to fix this let me know)
